export const BUILD_CPU_MODEL = "BUILD_CPU_MODEL";
export const BUILD_GPU_MODEL = "BUILD_GPU_MODEL";
export const BUILD_RAM_MODEL = "BUILD_RAM_MODEL";
export const BUILD_STORAGE_SIZE = "BUILD_STORAGE_SIZE";
export const BUILD_STORAGE_BRAND = "BUILD_STORAGE_BRAND";
export const BUILD_STORAGE_MODEL = "BUILD_STORAGE_MODEL";

export const BUILD_PC = "BUILD_PC";