export const BUILD_CPU_MODEL = "BUILD_CPU_MODEL";
export const BUILD_GPU_MODEL = "BUILD_GPU_MODEL";
export const BUILD_RAM_MODEL = "BUILD_RAM_MODEL";
export const BUILD_HDD_MODEL = "BUILD_HDD_MODEL";
export const BUILD_SSD_MODEL = "BUILD_SSD_MODEL";

export const BUILD_PC = "BUILD_PC";